#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f top.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc  --trace cache_top.sv cache.sv memory.sv --exe cache_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vcache_top.mk Vcache_top

# run executable simulation file
obj_dir/Vcache_top

#    ls /dev/tty.u*
#    /dev/tty.usbserial-110
#    /dev/ttyS3
#    chmod +x doit.sh